language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8.3

before_install:
  brew tap vapor/tap;
  brew update;
  brew install vapor;

script:
    - swift build
    - swift build -c release
    - swift package generate-xcodeproj
    - xcodebuild -scheme Sanitize -enableCodeCoverage YES test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)